#!/usr/bin/env python3
"""uv-native task runner for CORE Paper workflows."""

from __future__ import annotations

import argparse
import importlib.util
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
PY = [sys.executable]


def run_py(args: list[str]) -> None:
    subprocess.run(PY + args, cwd=ROOT, check=True)


def ensure_metaworld() -> None:
    if importlib.util.find_spec("metaworld") is None:
        raise SystemExit(
            "Missing optional dependency 'metaworld'. "
            "Run: uv sync --extra metaworld"
        )


def task_validate() -> None:
    run_py(["scripts/validate_all.py"])


def task_version_check() -> None:
    run_py(["scripts/version/check_version_sync.py"])


def task_version_snapshot() -> None:
    run_py(["scripts/version/write_version_snapshot.py"])


def task_version_bump() -> None:
    run_py(["scripts/version/bump_version.py"])


def task_pipeline_sanity() -> None:
    run_py(["scripts/paper/pipeline_sanity_checks.py"])


def task_ws0_refresh() -> None:
    run_py(["scripts/ws0/refresh_official_iros_2026_status.py"])


def task_literature_cycle() -> None:
    run_py(
        [
            "scripts/literature/fetch_arxiv.py",
            "--config",
            "config/literature_queries.json",
            "--max-results",
            "10",
            "--download-format",
            "html",
            "--metadata-out",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--download-dir",
            "data/papers/raw/arxiv_latest",
        ]
    )
    run_py(
        [
            "scripts/literature/ingest_documents.py",
            "--input-dir",
            "data/papers/raw/arxiv_latest",
            "--output-dir",
            "data/papers/ingested/arxiv_latest",
            "--records-out",
            "data/papers/ingested/arxiv_latest_records.jsonl",
        ]
    )
    run_py(
        [
            "scripts/literature/generate_weekly_delta.py",
            "--current",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--previous",
            "data/papers/metadata/arxiv_previous.jsonl",
            "--output",
            "output/corepaper_reports/literature/weekly_delta_latest.md",
        ]
    )
    run_py(
        [
            "scripts/literature/build_coverage_matrix.py",
            "--metadata",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--output",
            "output/corepaper_reports/literature/coverage_matrix_latest.md",
        ]
    )
    run_py(
        [
            "scripts/literature/extract_structured_evidence.py",
            "--metadata",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--ingested-records",
            "data/papers/ingested/arxiv_latest_records.jsonl",
            "--output-jsonl",
            "data/papers/structured/evidence_latest.jsonl",
            "--output-md",
            "output/corepaper_reports/literature/evidence_table_latest.md",
        ]
    )
    run_py(
        [
            "scripts/literature/generate_weekly_brief.py",
            "--metadata",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--structured-evidence",
            "data/papers/structured/evidence_latest.jsonl",
            "--delta",
            "output/corepaper_reports/literature/weekly_delta_latest.md",
            "--output",
            "output/corepaper_reports/literature/weekly_brief_latest.md",
        ]
    )
    run_py(
        [
            "scripts/literature/build_recent_baseline_candidates.py",
            "--metadata",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--output-json",
            "output/corepaper_reports/literature/recent_baseline_candidates.json",
            "--output-md",
            "output/corepaper_reports/literature/recent_baseline_candidates.md",
        ]
    )


def task_experiments_cycle() -> None:
    ensure_metaworld()
    run_py(["scripts/experiments/generate_benchmark_configs.py"])
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/experiments_smoke.json",
            "--output-dir",
            "output/corepaper_logs/experiments/latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/generate_regression_dashboard.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/latest",
            "--output",
            "output/corepaper_reports/experiments/regression_dashboard_latest.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/check_artifact_integrity.py",
            "--config",
            "config/experiments_smoke.json",
            "--logs-dir",
            "output/corepaper_logs/experiments/latest",
            "--output",
            "output/corepaper_reports/experiments/integrity_report_latest.json",
        ]
    )
    run_py(
        [
            "scripts/experiments/summarize_suite.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/latest",
            "--output-json",
            "output/corepaper_reports/experiments/summary_latest.json",
            "--output-md",
            "output/corepaper_reports/experiments/summary_latest.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_external_baselines.json",
            "--output-dir",
            "output/corepaper_logs/experiments/external_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_external_baselines.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/external_latest",
            "--output-json",
            "output/corepaper_reports/ws3/external_baseline_summary.json",
            "--output-md",
            "output/corepaper_reports/ws3/external_baseline_summary.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_external_baselines_n14.json",
            "--output-dir",
            "output/corepaper_logs/experiments/external_n14_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_external_baselines.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/external_n14_latest",
            "--output-json",
            "output/corepaper_reports/ws3/corepaper_external_n14_summary.json",
            "--output-md",
            "output/corepaper_reports/ws3/corepaper_external_n14_summary.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/compute_effect_sizes.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/external_n14_latest",
            "--output-json",
            "output/corepaper_reports/ws5/corepaper_external_n14_statistical_effects.json",
            "--output-md",
            "output/corepaper_reports/ws5/corepaper_external_n14_statistical_effects.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/corepaper_external_n14_statistical_effects.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_custom_n14.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_custom_n14.md",
            "--family-name",
            "custom-scenario-n14",
            "--rows-key",
            "rows",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_reliability_floor.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/external_n14_latest",
            "--reference-group",
            "method",
            "--comparator-group",
            "ext2",
            "--output-json",
            "output/corepaper_reports/ws5/corepaper_reliability_floor_n14.json",
            "--output-md",
            "output/corepaper_reports/ws5/corepaper_reliability_floor_n14.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_baseline_calibration.py",
            "--summary-json",
            "output/corepaper_reports/ws3/external_baseline_summary.json",
            "--targets-json",
            "config/benchmarks/baseline_calibration_targets.json",
            "--output-json",
            "output/corepaper_reports/ws3/baseline_calibration.json",
            "--output-md",
            "output/corepaper_reports/ws3/baseline_calibration.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/compute_effect_sizes.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/external_latest",
            "--output-json",
            "output/corepaper_reports/ws5/statistical_effects.json",
            "--output-md",
            "output/corepaper_reports/ws5/statistical_effects.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/statistical_effects.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_custom_n5.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_custom_n5.md",
            "--family-name",
            "custom-scenario-n5",
            "--rows-key",
            "rows",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_statistical_power.py",
            "--effects-json",
            "output/corepaper_reports/ws5/statistical_effects.json",
            "--output-json",
            "output/corepaper_reports/ws5/statistical_power.json",
            "--output-md",
            "output/corepaper_reports/ws5/statistical_power.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_ablation.json",
            "--output-dir",
            "output/corepaper_logs/experiments/ablation_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_ablation.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/ablation_latest",
            "--output-json",
            "output/corepaper_reports/ws5/ablation_results.json",
            "--output-md",
            "output/corepaper_reports/ws5/ablation_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_robustness.json",
            "--output-dir",
            "output/corepaper_logs/experiments/robustness_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_robustness.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/robustness_latest",
            "--nominal-summary",
            "output/corepaper_reports/experiments/summary_latest.json",
            "--output-json",
            "output/corepaper_reports/ws5/robustness_results.json",
            "--output-md",
            "output/corepaper_reports/ws5/robustness_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_software_transfer.json",
            "--output-dir",
            "output/corepaper_logs/experiments/software_transfer_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_software_transfer.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/software_transfer_latest",
            "--nominal-summary",
            "output/corepaper_reports/experiments/summary_latest.json",
            "--output-json",
            "output/corepaper_reports/ws5/software_transfer_results.json",
            "--output-md",
            "output/corepaper_reports/ws5/software_transfer_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_sim2sim.json",
            "--output-dir",
            "output/corepaper_logs/experiments/sim2sim_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_sim2sim.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/sim2sim_latest",
            "--nominal-summary",
            "output/corepaper_reports/experiments/summary_latest.json",
            "--output-json",
            "output/corepaper_reports/ws5/sim2sim_transfer_results.json",
            "--output-md",
            "output/corepaper_reports/ws5/sim2sim_transfer_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_recent_paper_baselines.json",
            "--output-dir",
            "output/corepaper_logs/experiments/recent_baselines_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_recent_paper_baselines.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/recent_baselines_latest",
            "--output-json",
            "output/corepaper_reports/ws5/recent_paper_baselines.json",
            "--output-md",
            "output/corepaper_reports/ws5/recent_paper_baselines.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_training_backed_recent.json",
            "--output-dir",
            "output/corepaper_logs/experiments/training_backed_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_recent_paper_baselines.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/training_backed_latest",
            "--output-json",
            "output/corepaper_reports/ws5/training_backed_recent.json",
            "--output-md",
            "output/corepaper_reports/ws5/training_backed_recent.md",
            "--comparators",
            "baseline,ext2,latency_aware,adaptmanip,robust_cp",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/training_backed_recent.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_training_backed.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_training_backed.md",
            "--family-name",
            "training-backed-stress",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/audit_official_library_parity.py",
            "--output-json",
            "output/corepaper_reports/ws5/library_parity_official.json",
            "--output-md",
            "output/corepaper_reports/ws5/library_parity_official.md",
            "--allow-stale-fallback",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_library_lane.json",
            "--output-dir",
            "output/corepaper_logs/experiments/library_lane_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_recent_paper_baselines.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/library_lane_latest",
            "--output-json",
            "output/corepaper_reports/ws5/library_lane.json",
            "--output-md",
            "output/corepaper_reports/ws5/library_lane.md",
            "--comparators",
            "sb3_ppo,rllib_sac",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/library_lane.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_library_lane.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_library_lane.md",
            "--family-name",
            "library-lane-stress",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_harness.py",
            "--config",
            "config/benchmarks/experiments_o2o_proxy_recent.json",
            "--output-dir",
            "output/corepaper_logs/experiments/o2o_proxy_latest",
            "--clean-output-dir",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_recent_paper_baselines.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/o2o_proxy_latest",
            "--output-json",
            "output/corepaper_reports/ws5/o2o_proxy_recent.json",
            "--output-md",
            "output/corepaper_reports/ws5/o2o_proxy_recent.md",
            "--comparators",
            "baseline,ext2,latency_aware,adaptmanip,robust_cp",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_o2o_failure_accounting.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/o2o_proxy_latest",
            "--output-json",
            "output/corepaper_reports/ws5/o2o_failure_accounting.json",
            "--output-md",
            "output/corepaper_reports/ws5/o2o_failure_accounting.md",
            "--comparators",
            "baseline,ext2,latency_aware,adaptmanip,robust_cp",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/o2o_proxy_recent.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_o2o_proxy.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_o2o_proxy.md",
            "--family-name",
            "o2o-proxy-stress",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_verification_first.py",
            "--recent-json",
            "output/corepaper_reports/ws5/o2o_proxy_recent.json",
            "--o2o-failure-json",
            "output/corepaper_reports/ws5/o2o_failure_accounting.json",
            "--output-json",
            "output/corepaper_reports/ws5/verification_first_diagnostics.json",
            "--output-md",
            "output/corepaper_reports/ws5/verification_first_diagnostics.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/generate_adversarial_shift_stress.py",
            "--top-k",
            "12",
            "--seed-end",
            "8",
            "--output-json",
            "config/benchmarks/experiments_adversarial_stress_generated.json",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_adversarial_stress_suite.py",
            "--config-json",
            "config/benchmarks/experiments_adversarial_stress_generated.json",
            "--output-json",
            "output/corepaper_reports/ws5/adversarial_stress_results.json",
            "--output-md",
            "output/corepaper_reports/ws5/adversarial_stress_results.md",
            "--comparators",
            "baseline,ext2,latency_aware,adaptmanip,robust_cp",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/adversarial_stress_results.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_adversarial_stress.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_adversarial_stress.md",
            "--family-name",
            "adversarial-composed-shifts",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_risk_budget_schedule.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/recent_baselines_latest",
            "--variant",
            "method",
            "--output-json",
            "output/corepaper_reports/ws5/risk_budget_schedule.json",
            "--output-md",
            "output/corepaper_reports/ws5/risk_budget_schedule.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws5/recent_paper_baselines.json",
            "--output-json",
            "output/corepaper_reports/ws5/pvalue_corrections_recent_stress.json",
            "--output-md",
            "output/corepaper_reports/ws5/pvalue_corrections_recent_stress.md",
            "--family-name",
            "recent-stress",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_slice.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_slice_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_slice_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_slice_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_slice_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_slice_stats.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_recent_baselines.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_stats.md",
            "--comparators",
            "baseline,ext1,ext2,latency_aware,adaptmanip,robust_cp,history_keyframe,constrained_flow",
        ]
    )
    run_py(
        [
            "scripts/experiments/audit_recent_baseline_official_parity.py",
            "--sources-json",
            "config/benchmarks/recent_baseline_official_sources.json",
            "--metadata-jsonl",
            "data/papers/metadata/arxiv_latest.jsonl",
            "--raw-paper-html",
            "data/papers/raw/iros2026_lit_raw/2602.14255v1/paper.html",
            "--results-json",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_results.json",
            "--output-json",
            "output/corepaper_reports/ws5/latency_aware_official_parity_audit.json",
            "--output-md",
            "output/corepaper_reports/ws5/latency_aware_official_parity_audit.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_stats.json",
            "--output-json",
            "output/corepaper_reports/ws3/pvalue_corrections_metaworld_recent.json",
            "--output-md",
            "output/corepaper_reports/ws3/pvalue_corrections_metaworld_recent.md",
            "--family-name",
            "metaworld-shifted-recent",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_maniskill_proxy_slice.py",
            "--config",
            "config/benchmarks/experiments_maniskill_proxy_recent.json",
            "--output-json",
            "output/corepaper_reports/ws3/maniskill_proxy_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/maniskill_proxy_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/maniskill_proxy_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/maniskill_proxy_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/maniskill_proxy_stats.md",
            "--comparators",
            "baseline,ext1,ext2,latency_aware,adaptmanip,robust_cp",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws3/maniskill_proxy_stats.json",
            "--output-json",
            "output/corepaper_reports/ws3/pvalue_corrections_maniskill_proxy.json",
            "--output-md",
            "output/corepaper_reports/ws3/pvalue_corrections_maniskill_proxy.md",
            "--family-name",
            "maniskill-proxy-shifted",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_cross_embodiment_proxy_slice.py",
            "--config",
            "config/benchmarks/experiments_cross_embodiment_proxy_recent.json",
            "--output-json",
            "output/corepaper_reports/ws3/cross_embodiment_proxy_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/cross_embodiment_proxy_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_cross_embodiment_transfer.py",
            "--input-json",
            "output/corepaper_reports/ws3/cross_embodiment_proxy_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/cross_embodiment_proxy_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/cross_embodiment_proxy_stats.md",
            "--comparators",
            "baseline,ext1,ext2,latency_aware,adaptmanip,robust_cp",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_pvalue_corrections.py",
            "--input-json",
            "output/corepaper_reports/ws3/cross_embodiment_proxy_stats.json",
            "--output-json",
            "output/corepaper_reports/ws3/pvalue_corrections_cross_embodiment_proxy.json",
            "--output-md",
            "output/corepaper_reports/ws3/pvalue_corrections_cross_embodiment_proxy.md",
            "--family-name",
            "cross-embodiment-proxy-shifted",
            "--rows-key",
            "comparisons",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_seedexp_ext2_method.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_ext2_method_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_ext2_method_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_ext2_method_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_ext2_method_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_ext2_method_stats.md",
            "--comparators",
            "ext2",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_seedexp_latency_method.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_stats.md",
            "--comparators",
            "latency_aware",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_seedexp_latency_method_n30.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_stats.md",
            "--comparators",
            "latency_aware",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_seedexp_adaptmanip_method.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_stats.md",
            "--comparators",
            "adaptmanip",
        ]
    )
    run_py(
        [
            "scripts/experiments/run_metaworld_slice.py",
            "--config",
            "config/benchmarks/experiments_metaworld_seedexp_adaptmanip_method_n30.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_results.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_results.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_metaworld_slice_stats.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_results.json",
            "--output-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_stats.json",
            "--output-md",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_stats.md",
            "--comparators",
            "adaptmanip",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_adapt_equivalence.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_results.json",
            "--reference-variant",
            "method",
            "--comparator-variant",
            "adaptmanip",
            "--scenario",
            "shifted",
            "--equivalence-margin",
            "0.05",
            "--bootstrap-samples",
            "10000",
            "--output-json",
            "output/corepaper_reports/ws5/metaworld_adapt_equivalence_n14.json",
            "--output-md",
            "output/corepaper_reports/ws5/metaworld_adapt_equivalence_n14.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_cvar_alpha_sensitivity.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_results.json",
            "--reference-group",
            "method",
            "--comparator-group",
            "latency_aware",
            "--alphas",
            "0.1,0.2,0.3,0.4,0.5",
            "--output-json",
            "output/corepaper_reports/ws5/metaworld_cvar_sensitivity_latency_n30.json",
            "--output-md",
            "output/corepaper_reports/ws5/metaworld_cvar_sensitivity_latency_n30.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_cvar_alpha_sensitivity.py",
            "--input-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_results.json",
            "--reference-group",
            "method",
            "--comparator-group",
            "adaptmanip",
            "--alphas",
            "0.1,0.2,0.3,0.4,0.5",
            "--output-json",
            "output/corepaper_reports/ws5/metaworld_cvar_sensitivity_adaptmanip_n30.json",
            "--output-md",
            "output/corepaper_reports/ws5/metaworld_cvar_sensitivity_adaptmanip_n30.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_uncertainty_dominance.py",
            "--logs-dirs",
            ",".join(
                [
                    "output/corepaper_logs/experiments/external_latest",
                    "output/corepaper_logs/experiments/robustness_latest",
                    "output/corepaper_logs/experiments/software_transfer_latest",
                    "output/corepaper_logs/experiments/sim2sim_latest",
                    "output/corepaper_logs/experiments/recent_baselines_latest",
                ]
            ),
            "--output-json",
            "output/corepaper_reports/ws5/uncertainty_dominance.json",
            "--output-md",
            "output/corepaper_reports/ws5/uncertainty_dominance.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_uncertainty_misspec_sensitivity.py",
            "--logs-dirs",
            ",".join(
                [
                    "output/corepaper_logs/experiments/external_latest",
                    "output/corepaper_logs/experiments/robustness_latest",
                    "output/corepaper_logs/experiments/software_transfer_latest",
                    "output/corepaper_logs/experiments/sim2sim_latest",
                    "output/corepaper_logs/experiments/recent_baselines_latest",
                ]
            ),
            "--uncertainty-json",
            "output/corepaper_reports/ws5/uncertainty_dominance.json",
            "--output-json",
            "output/corepaper_reports/ws5/uncertainty_misspec_sensitivity.json",
            "--output-md",
            "output/corepaper_reports/ws5/uncertainty_misspec_sensitivity.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_prop2_ordering.py",
            "--logs-dir",
            "output/corepaper_logs/experiments/recent_baselines_latest",
            "--reference-variant",
            "method",
            "--comparators",
            "adaptmanip,latency_aware",
            "--output-json",
            "output/corepaper_reports/ws5/prop2_ordering_proxy.json",
            "--output-md",
            "output/corepaper_reports/ws5/prop2_ordering_proxy.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_budget_parity.py",
            "--input-jsons",
            ",".join(
                [
                    "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_results.json",
                    "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_results.json",
                    "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_results.json",
                    "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_results.json",
                ]
            ),
            "--reference-variant",
            "method",
            "--output-json",
            "output/corepaper_reports/ws5/metaworld_budget_parity.json",
            "--output-md",
            "output/corepaper_reports/ws5/metaworld_budget_parity.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_theorem1_neff.py",
            "--input-jsons",
            ",".join(
                [
                    "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_results.json",
                    "output/corepaper_reports/ws3/metaworld_seedexp_adaptmanip_method_n30_results.json",
                ]
            ),
            "--reference-variant",
            "method",
            "--scenario",
            "shifted",
            "--output-json",
            "output/corepaper_reports/ws5/theorem1_neff_diagnostic.json",
            "--output-md",
            "output/corepaper_reports/ws5/theorem1_neff_diagnostic.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_gate_threshold_sensitivity.py",
            "--cycles-dir",
            "output/corepaper_logs/ws4/cycles",
            "--output-json",
            "output/corepaper_reports/ws5/gate_threshold_sensitivity.json",
            "--output-md",
            "output/corepaper_reports/ws5/gate_threshold_sensitivity.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_gate_decision_quality.py",
            "--cycles-dir",
            "output/corepaper_logs/ws4/cycles",
            "--tau-green",
            "0.02",
            "--tau-yellow",
            "0.005",
            "--output-json",
            "output/corepaper_reports/ws5/gate_decision_quality.json",
            "--output-md",
            "output/corepaper_reports/ws5/gate_decision_quality.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/summarize_validity_gap.py",
            "--recent-json",
            "output/corepaper_reports/ws5/recent_paper_baselines.json",
            "--metaworld-json",
            "output/corepaper_reports/ws3/metaworld_recent_baselines_stats.json",
            "--output-json",
            "output/corepaper_reports/review_readiness/validity_gap_status.json",
            "--output-md",
            "output/corepaper_reports/review_readiness/validity_gap_status.md",
        ]
    )
    run_py(
        [
            "scripts/experiments/analyze_ceiling_regime.py",
            "--recent-json",
            "output/corepaper_reports/ws5/recent_paper_baselines.json",
            "--metaworld-json",
            "output/corepaper_reports/ws3/metaworld_seedexp_latency_method_n30_stats.json",
            "--output-json",
            "output/corepaper_reports/ws5/ceiling_regime_diagnostics.json",
            "--output-md",
            "output/corepaper_reports/ws5/ceiling_regime_diagnostics.md",
        ]
    )
    run_py(["scripts/paper/generate_result_macros.py"])


def task_figures() -> None:
    run_py(["scripts/figures/generate_paper_figures.py"])
    run_py(["scripts/figures/export_png_figures.py", "--with-png"])
    run_py(["scripts/figures/audit_visual_consistency.py"])


def task_media() -> None:
    run_py(["scripts/vis/build_video_pipeline.py"])


def task_anonymous_release() -> None:
    run_py(
        [
            "scripts/review_readiness/build_anonymous_release.py",
            "--output-zip",
            "output/corepaper_submission/corepaper_anonymous_release.zip",
        ]
    )


def task_review_readiness_claude_critique() -> None:
    run_py(["scripts/review_readiness/run_bedrock_claude_critique.py"])


def task_review_readiness_counsel_critique() -> None:
    run_py(["scripts/review_readiness/run_llm_counsel_critique.py"])


def task_bundle() -> None:
    run_py(["scripts/paper/generate_draft_manuscript.py"])
    run_py(
        [
            "scripts/paper/generate_simple_pdf.py",
            "--input",
            "output/corepaper_submission/corepaper_main_paper_draft.md",
            "--output",
            "output/corepaper_submission/corepaper_main_paper_draft.pdf",
            "--title",
            "CORE Paper Draft",
        ]
    )
    run_py(["scripts/paper/build_submission_bundle.py", "--bundle-dir", "output/corepaper_submission"])


def task_repro_audit() -> None:
    run_py(["scripts/review_readiness/run_repro_audit.py", "--output", "docs/review_readiness/repro-audit-report.md"])


def task_weekly_cycle() -> None:
    ensure_metaworld()
    run_py(["scripts/orchestration/run_weekly_cycle.py"])


def task_paper_pipeline() -> None:
    """Run the full paper pipeline in one entrypoint."""
    task_experiments_cycle()
    task_figures()
    run_py(["scripts/paper/build_iros2026_pdf_docker.py"])
    task_validate()
    task_pipeline_sanity()


TASKS = {
    "validate": task_validate,
    "version-check": task_version_check,
    "version-bump": task_version_bump,
    "version-snapshot": task_version_snapshot,
    "pipeline-sanity": task_pipeline_sanity,
    "ws0-refresh": task_ws0_refresh,
    "literature-cycle": task_literature_cycle,
    "experiments-cycle": task_experiments_cycle,
    "figures": task_figures,
    "media": task_media,
    "anonymous-release": task_anonymous_release,
    "review-readiness-claude-critique": task_review_readiness_claude_critique,
    "review-readiness-counsel-critique": task_review_readiness_counsel_critique,
    "bundle": task_bundle,
    "repro-audit": task_repro_audit,
    "weekly-cycle": task_weekly_cycle,
    "paper-pipeline": task_paper_pipeline,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("task", choices=sorted(TASKS))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    TASKS[args.task]()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
